### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sjlawton/proj10#1]
This looks mostly really good. There are just a couple things I'd like you to update:
### Styles spread across files

In this case, I'm not sure there's any value in spreading these styles across different files in the `stylesheets` folder. I would delete either `static.css` or `custom.css`, then move all the styles into the one you didn't delete. Let me know if that makes sense.
### Indentation

I see some inconsistent indentation and some indentation that isn't two-space soft-tabs (I _think_ just in the stylesheets). The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

---

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by sjlawton** [comment]
should be fixed now

**Comment by chrisvfritz** [comment]
The indentation looks great now, but I still see 2 files specifying the background of the body: `static.css` and `application.css`. Could you delete one and keep the body background you want to keep in `static.css`?

**Comment by sjlawton** [comment]
should be fine now

**Comment by chrisvfritz** [comment]
:+1: Looks great!
